### ISSUE TITLE
Enhancement : Reporting Skipped Tests

### ISSUE THREAD

**Issue by AbdelghaniDr** [joakimkarlsson/igloo#20]
Hi, 
First I'd like to thank you for a header-only-easy-to-use testing framework;

I would like to know if there's a way to report Skipped tests at the end of the execution because I tend to mark some with  "_Skip" in order to fix some other parts of the code and it'll be nice if the default test runner reported them ( with test names ) so I can go back and remove  the "_Skip" part to re-enable them.

Thanks again for the good work !

**Comment by joakimkarlsson** [comment]
I'd be happy to consider a pull request for such a feature. Perhaps it's better to not change the default outputter, but create a new outputter instead.

Take a look att https://github.com/joakimkarlsson/igloo/tree/master/igloo/core/outputters to see how the current outputters are implemented.
