### ISSUE TITLE
Documentation link is no longer valid

### ISSUE THREAD

**Issue by panozzaj** [joakimkarlsson/igloo#22]
Seems that http://igloo-testing.org/ is held by someone else? It automatically downloads Flash DMGs, etc. when you go there. This link is referenced in the Github project's description and the README.

For others who are looking for the documentation, the latest archive I can find is at https://web.archive.org/web/20171217153921/http://igloo-testing.org/ , although it doesn't seem to contain much besides what is contained in the README.

My proposal would be to remove the link for now since it's potentially harmful and doesn't contain any information at the moment.

**Comment by panozzaj** [comment]
Looks like there is also a Wordpress blog that has roughly the same info: https://iglootesting.wordpress.com/

**Comment by joakimkarlsson** [comment]
Fixed.  ...finally.
